//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication6.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HC_USER_MAIN
    {
        public long RID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string MiddleName { get; set; }
        public string EmailID { get; set; }
        public string MobileNo { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public Nullable<long> ReportingToID { get; set; }
        public bool Status { get; set; }
        public string Notes { get; set; }
        public long CreatedUserID { get; set; }
        public Nullable<long> ModifiedUserID { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public long TID { get; set; }
        public Nullable<System.DateTime> LstLgnFailedAttempt { get; set; }
        public Nullable<short> LastLoginFailedAttemptCnt { get; set; }
        public Nullable<System.DateTime> LastPasswordExpiryDate { get; set; }
        public Nullable<short> IsFirstTimeLogin { get; set; }
        public Nullable<long> Salutation { get; set; }
        public string PhoneNo { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public long ConfigTemplateID { get; set; }
        public string Photo { get; set; }
        public Nullable<long> GradeID { get; set; }
        public string ForgotPswKey { get; set; }
        public bool IsAdmin { get; set; }
        public long DesignationID { get; set; }
        public Nullable<long> GenderID { get; set; }
        public string Keys { get; set; }
        public Nullable<long> Pin { get; set; }
        public Nullable<System.DateTime> KeyExpiryTime { get; set; }
        public bool IsPrimary { get; set; }
        public string EmailSignature { get; set; }
        public Nullable<long> NationalityID { get; set; }
        public bool IsDataSync { get; set; }
        public Nullable<System.DateTime> LastDataSyncDate { get; set; }
        public Nullable<long> TimeZone { get; set; }
        public Nullable<long> ContactRoleID { get; set; }
        public Nullable<System.DateTime> LastLoginDate { get; set; }
        public string EmployerID { get; set; }
        public Nullable<short> CalendarDefaultViewId { get; set; }
        public Nullable<long> BloodGroupId { get; set; }
        public string MobileNoExt { get; set; }
        public Nullable<long> WorkLocationID { get; set; }
        public Nullable<short> MaritalStatus { get; set; }
        public string ReportingManagerName { get; set; }
        public string DigiSignData { get; set; }
        public string DigiSignPassword { get; set; }
        public string ActualEmailID { get; set; }
        public string DigiSignName { get; set; }
        public string MobileNo2 { get; set; }
        public Nullable<long> DOBCityID { get; set; }
        public Nullable<long> DOBStateID { get; set; }
        public Nullable<long> DOBCountryID { get; set; }
        public string FatherName { get; set; }
        public string PhoneNoExt { get; set; }
        public string NameAsAadhar { get; set; }
        public long V4RID { get; set; }
        public string MigratedDataFrom { get; set; }
        public Nullable<long> V3V4RID { get; set; }
        public string isMigrated { get; set; }
        public Nullable<long> CurrencyID { get; set; }
        public string DateFormat { get; set; }
        public Nullable<long> DurationID { get; set; }
        public Nullable<short> SyncDataManually { get; set; }
    }
}
